# Generated by Django 4.1 on 2022-08-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCS_task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='transaction_id',
            field=models.CharField(default='SOME STRING', max_length=255),
        ),
    ]
