# Generated by Django 4.1 on 2022-08-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCS_task', '0003_translation_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translation',
            options={'ordering': ['-time_create'], 'verbose_name': 'Список транзакций', 'verbose_name_plural': 'Список транзакций'},
        ),
        migrations.AlterField(
            model_name='translation',
            name='description',
            field=models.TextField(default='some description', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='время создания'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='transaction_id',
            field=models.CharField(default='some id', max_length=255, verbose_name='ID транзакции'),
        ),
    ]
